pipeline {
    agent none

    parameters {
        string(description: 'Git tag on which to base build', name: 'h4ciTag', defaultValue: '2.1.1.6.devel')
    }

    options {
      timestamps()
    }

    environment {
        GIT_LFS_SKIP_SMUDGE = '1'
        HOME = '/home/h4re1'
    }
    stages {
        stage('Update Dashboard') {
          agent {
            label 'el-7'
          }
          steps {
            def status = sh(returnStatus: true, script: "echo \${params.h4ciTag} | grep -q -E '.devel\$'")
            if (status == 0 ) {

                sh(script: 'mysql -hdashboard.tetrationanalytics.com dashboard_db -e "select tag from cr_builds;"', returnStdout: true)
            }
          }
        }
    }
}
